org: devingen
app: devingen-io
service: sepet-api

frameworkVersion: '^3.1.1'

provider:
  name: aws
  runtime: go1.x
  environment:
    SEPET_API_S3_ACCESS_KEY_ID: ${param:SEPET_API_S3_ACCESS_KEY_ID}
    SEPET_API_S3_SECRET_ACCESS_KEY: ${param:SEPET_API_S3_SECRET_ACCESS_KEY}
    SEPET_API_S3_REGION: ${param:SEPET_API_S3_REGION}
    SEPET_API_MONGO_URI: ${param:SEPET_API_MONGO_URI}
    SEPET_API_MONGO_DATABASE: ${param:SEPET_API_MONGO_DATABASE}
    SEPET_API_S3_BUCKET: ${param:SEPET_API_S3_BUCKET}
    SEPET_API_WEBHOOK_URL: ${param:SEPET_API_WEBHOOK_URL}
    SEPET_API_WEBHOOK_HEADERS: ${param:SEPET_API_WEBHOOK_HEADERS}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:

  get-buckets:
    handler: bin/get-buckets
    events:
      - http:
          path: /buckets
          method: get
          cors:
            headers: "*"

  create-bucket:
    handler: bin/create-bucket
    events:
      - http:
          path: /buckets
          method: post
          cors:
            headers: "*"

  get-bucket:
    handler: bin/get-bucket
    events:
      - http:
          path: /buckets/{id}
          method: get
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                id: true

  update-bucket:
    handler: bin/update-bucket
    events:
      - http:
          path: /buckets/{id}
          method: put
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                id: true

  delete-bucket:
    handler: bin/delete-bucket
    events:
      - http:
          path: /buckets/{id}
          method: delete
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                id: true

  get-bucket-version-list:
    handler: bin/get-bucket-version-list
    events:
      - http:
          path: /buckets/{id}/versions
          method: get
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                id: true

  upload-file:
    handler: bin/upload-file
    events:
      - http:
          path: /{domain}
          method: post
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                domain: true

  get-file-list-or-delete-file:
    handler: bin/get-file-list-or-delete-file
    events:
      - http:
          path: /{domain+}
          method: any
          cors:
            headers: "*"
